name: Code Styling

on:
  pull_request:
    paths:
      - "**.py"
  push:
    branches:
      - master
    paths:
      - "**.py"
  workflow_dispatch:
  workflow_call:

jobs:
  code_style_checking:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Load cache (if exists)
        uses: actions/cache@v2.1.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip
      - name: Install Styling Tools
        run: python -m pip install isort black flake8 pylint
      - name: Run linters
        run: |
          isort regexfactory --check
          black regexfactory --check
          pylint regexfactory
  
  type_checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo

      - uses: jpetrucciani/mypy-check@master
        with:
          path: regexfactory
